# This for correct LSP using mingw on Windows
# CLANGD CONFIG PATH: $env:LOCALAPPDATA\clangd\config.yaml
If:
  PathMatch: .*\.c
CompileFlags:
  Compiler: gcc
---
If:
  PathMatch: .*\.cpp
CompileFlags:
  Compiler: g++
---
