[font]
size = 17

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "t"
mods = "Alt"

[window]
opacity = 1
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
