[font]
size = 16

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono NF"
style = "Bold"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "t"
mods = "Alt"

[window]
opacity = 1
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
