[font]
size = 15

[env]
TERM = "xterm-256color"

[font.normal]
family = "Roboto Mono"

[shell]
program = "pwsh"
args = ["-NoLogo", "-NoExit", "-Command", "cd ~" ]

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "t"
mods = "Alt"

[window]
opacity = 1
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"
